# Generated by Django 2.2 on 2019-05-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0005_order_price_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_order',
        ),
    ]
