# Generated by Django 2.2 on 2019-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0006_remove_order_price_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phon_number',
            field=models.IntegerField(default=8, verbose_name='رقم الهاتف '),
        ),
    ]
