# Generated by Django 2.2 on 2019-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0007_order_phon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phon_number',
            field=models.IntegerField(blank=True, verbose_name='رقم الهاتف '),
        ),
    ]
