# Generated by Django 2.2 on 2019-05-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0008_auto_20190521_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name_meal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الوجبة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='meal_list.Meal'),
        ),
    ]
