# Generated by Django 2.2 on 2019-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0009_auto_20190522_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(upload_to='meal-img'),
        ),
    ]
