# Generated by Django 2.2 on 2019-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0010_auto_20190522_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(upload_to='meal-img/%Y/%m/%d'),
        ),
    ]
