# Generated by Django 2.2 on 2019-05-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0016_auto_20190522_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, upload_to='meal-img/%Y/%m/%d'),
        ),
    ]
