# Generated by Django 2.2 on 2019-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0017_auto_20190522_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
