# Generated by Django 2.2 on 2019-05-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0026_auto_20190522_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal-img'),
        ),
    ]
