# Generated by Django 2.2 on 2019-05-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0027_auto_20190522_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
