# Generated by Django 2.2 on 2019-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0029_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
