# Generated by Django 2.2 on 2019-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0033_remove_meal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
    ]
