# Generated by Django 2.2 on 2019-05-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_list', '0035_auto_20190527_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='meal_list.Meal'),
        ),
    ]
